version: "3.3"

services:  

  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      pubapi:
        aliases:
          - mongodb

  addressbook:    
   image: addressbook 
   build: ./addressbook                
   container_name: addressbook
   links:
      - mongodb
   environment:
    - JVM_OPTS=-Xmx1g -Xms1g -XX:MaxPermSize=4g
    - CATALINA_OPTS=-Xmx1g -Xms1g -XX:MaxPermSize=4g 
   ports:
    - '2021:2021'  
   networks:
    - pubapi
    
networks:
  pubapi:
    driver: bridge
